// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_itC7kszD-19idC_HpLc_WMwKf4xcO1E',
    appId: '1:134097653278:web:6bbdbf64db7b6bb623a80f',
    messagingSenderId: '134097653278',
    projectId: 'baatkaro-283f1',
    authDomain: 'baatkaro-283f1.firebaseapp.com',
    storageBucket: 'baatkaro-283f1.firebasestorage.app',
    measurementId: 'G-QNG1150Y6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXcuZfT67GPbEj99SxANliwrMdufHdgQs',
    appId: '1:134097653278:android:adac64bfecd7419523a80f',
    messagingSenderId: '134097653278',
    projectId: 'baatkaro-283f1',
    storageBucket: 'baatkaro-283f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvVd7zhVuWmwtx6oSkR3Chfyf4O_-ADhc',
    appId: '1:134097653278:ios:9e5a65baf4fad2f823a80f',
    messagingSenderId: '134097653278',
    projectId: 'baatkaro-283f1',
    storageBucket: 'baatkaro-283f1.firebasestorage.app',
    iosBundleId: 'com.example.baatkaro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvVd7zhVuWmwtx6oSkR3Chfyf4O_-ADhc',
    appId: '1:134097653278:ios:9e5a65baf4fad2f823a80f',
    messagingSenderId: '134097653278',
    projectId: 'baatkaro-283f1',
    storageBucket: 'baatkaro-283f1.firebasestorage.app',
    iosBundleId: 'com.example.baatkaro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_itC7kszD-19idC_HpLc_WMwKf4xcO1E',
    appId: '1:134097653278:web:ec64ae63e02a1f6b23a80f',
    messagingSenderId: '134097653278',
    projectId: 'baatkaro-283f1',
    authDomain: 'baatkaro-283f1.firebaseapp.com',
    storageBucket: 'baatkaro-283f1.firebasestorage.app',
    measurementId: 'G-SXSS62D8FX',
  );
}
